version: 0.0

os: linux

files: 
  - source: /
    destination: /home/ec2-user
    
permissions: 
  - object: /home/ec2-user
    pattern: "*.sh"
    owner: ec2-user
    mode: 700
    
hooks:
  AfterInstall:
  - location: add_privileges.sh
    timeout: 300
  ApplicationStart:
  - location: start.sh
    timeout: 300
  ApplicationStop:
  - location: stop.sh
    timeout: 300