version: 0.0

os: linux

files: 
  - source: aws-pipeline-example-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/aws-pipeline-example-0.0.1-SNAPSHOT.jar
  - source: start.sh
    destination: /home/ec2-user/start.sh
  - source: stop.sh
    destination: /home/ec2-user/stop.sh
  - source: appspec.yml
    destination: /home/ec2-user/appspec.yml
    
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 200
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 200
      runas: ec2-user
