version: 0.0

os: linux

files: 
  - source: /
    destination: /home/ec2-user
    
hooks:
  AfterInstall:
  - location: add_privileges.sh
    timeout: 300
  ApplicationStart:
  - location: start.sh
    timeout: 300
  ApplicationStop:
  - location: stop.sh
    timeout: 300